# Introduction to Python

## Course Description

Python is a general-purpose programming language that is becoming ever more popular for data science. Companies worldwide are using Python to harvest insights from their data and gain a competitive edge. Unlike other Python tutorials, this course focuses on Python specifically for data science. In our Introduction to Python course, you’ll learn about powerful ways to store and manipulate data, and helpful data science tools to begin conducting your own analyses. Start DataCamp’s online Python curriculum now.

## 1. Chapter 1 - Python Basics

An introduction to the basic concepts of Python. Learn how to use Python interactively and by using a script. Create your first variables and acquaint yourself with Python's basic data types.

- Guido Van Rossum
- General Purpose: build anything
- Open Source! Free!
- Python Packages, also for Data Science
- Many applications and fields

### Python Script
- Text Files - .py
- List of Python Commands
- Similar to typing in IPython Shell

Python is a pretty versatile language. For which applications can you use Python?

- You want to do some quick calculations.
- For your new business, you want to develop a database-driven website.
- Your boss asks you to clean and analyze the results of the latest satisfaction survey.
- You can all of the above tasks using Python.

### Comments :
You can add comments to your Python scripts. Comments are important to make
sure that you and others can understand what your code is about.
To add comments to your Python script, you can use the `# tag`. These comments
are not run as Python code, so they will not influence your result.

In [10]:
# Example, do not modify!
print(5 / 8)

# Print the sum of 7 and 10
print(7 + 10)

0.625
17


### Python as a calculator
Python is perfectly suited to do basic calculations. It can do addition, subtraction, multiplication and division.
The code in the script gives some examples.
Now it's your turn to practice!

#### Instructions

- Print the sum of 4 + 5.
- Print the result of subtracting 5 from 5.
- Print the result of multiplying 3 by 5.
- Print the result of dividing 10 by 2

In [11]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100 * 1.1 ** 7)

10
0
15
5.0
4
16
194.87171000000012


### Variables and Types

#### Variables
- Specific, case-sensitive 
- nameCall up value through variable name
- 1.79 m - 68.7 kg

#### Calculate BMI


The BMI formula is:  $BMI = \frac{weight}{height^2}$


In [12]:
# Example

height = 1.79 
weight = 68.7  
# print(height) 
# print(weight)

bmi = weight / height ** 2
print(bmi)

21.44127836209856


In [13]:
# Python Types

# types(1)

print(type(bmi)) 

day_of_week = 5 
print(type(day_of_week)) 

# Types (2)
x = "body mass index" 
y = 'this works too'  
print(type(x)) 
print(type(y))

z = True 
print(type(z)) 

# Types (3) - NB:  Different type = different behavior!
print(2 + 3 )
print('ab' + 'cd') 

# Different type = different behavior!

<class 'float'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'bool'>
5
abcd


### Variable Assignment

#### Instructions

- Create a variable savings with the value of 100.
- Check out this variable by typing print(savings) in the script.


In [14]:
# Create a variable savings
savings = 100

# Print out savings
print(savings)

100


### Calculations with variables

You've now created a savings variable, so let's start saving!

Instead of calculating with the actual values, you can use variables instead. The savings variable you created in the previous exercise with a value of 100 is available to you.

How much money would you have saved four months from now, if you saved $10 each month?

#### Instructions

- Create a variable monthly_savings, equal to 10 and num_months, equal to 4.
- Multiply monthly_savings by num_months and save it to new_savings.
- Add new_savings to savings, saving the sum as total_savings.
- Print the value of total_savings

In [15]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = savings * growth_multiplier ** 7

# Print out result
print(result)

194.87171000000012


You've now created a savings variable, so let's start saving!

Instead of calculating with the actual values, you can use variables instead. The savings variable you created in the previous exercise with a value of 100 is available to you.

How much money would you have saved four months from now, if you saved $10 each month?

#### Instructions

- Create a variable monthly_savings, equal to 10 and num_months, equal to 4.
- Multiply monthly_savings by num_months and save it to new_savings.
- Add new_savings to savings, saving the sum as total_savings.
- Print the value of total_savings.

In [16]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = savings * growth_multiplier ** 7

# Print out result
print(result)

monthly_savings = 10
num_months = 4 
new_savings = monthly_savings * num_months
total_savings = new_savings + savings
print(total_savings)

194.87171000000012
140


### Other variable types
In the previous exercise, you worked with the integer Python data type:

- *`int, or integer:`* a number without a fractional part. savings, with the value 100, is an example of an integer.

Next to numerical data types, there are three other very common data types:

- *`float, or floating point:`* a number that has both an integer and fractional part, separated by a point. 1.1, is an example of a float.
- *`str, or string:`* a type to represent text. You can use single or double quotes to build a string.
- *`bool, or boolean:`* a type to represent logical values. It can only be True or False (the capitalization is important!).


#### Instructions

- Create a new float, `half`, with the value `0.5`.
- Create a new string, `intro`, with the value `"Hello! How are you?"`.
- Create a new boolean, `is_good`, with the value `True`.

In [17]:
# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True
half = 0.5
intro = "Hello! How are you?"
is_good = True

#### Operations with other types

When you sum two strings, for example, you'll get different behavior than when you sum two integers or two booleans.

In the script some variables with different types have already been created. It's up to you to use them.

#### Instructions

- Calculate the product of monthly_savings and num_months. Store the result in year_savings.
- What do you think the resulting type will be? Find out by printing out the type of year_savings.
- Calculate the sum of intro and intro and store the result in a new variable doubleintro.
- Print out doubleintro. Did you expect this?

In [18]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of savings and growth_multiplier to year1
year1 = savings * growth_multiplier

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc =  desc + desc

# Print out doubledesc
print(doubledesc)

monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"

year_savings = monthly_savings * num_months
print(type(year_savings))

doubleintro = intro + intro
print(doubleintro)

<class 'float'>
compound interestcompound interest
<class 'int'>
Hello! How are you?Hello! How are you?


### Type conversion
Using the `+` operator to paste together two strings can be very useful in building custom messages.

Suppose, for example, that you've calculated your savings want to summarize the results in a string.

To do this, you'll need to explicitly convert the types of your variables. More specifically, you'll need `str()`, to convert a value into a string. `str(savings)`, for example, will convert the integer savings to a string.

Similar functions such as `int()`, `float()` and `bool()` will help you convert Python values into any type.

- Fix the code such that the printout runs without errors; use the function `str()` to convert the variables `savings` and `total_savings` to strings.
- Convert the variable `pi_string` to a float and store this float as a new variable, `pi_float`.

In [19]:
# Definition of savings and result
savings = 100
total_savings = 150

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(total_savings) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $150. Awesome!


# Chapter 2 - Python Lists

Learn to store, access, and manipulate data in lists: the first step toward efficiently working with huge amounts of data.

### Python Data Types

- float - real numbers
- int - integer numbers
- str - string, text
- bool - True, False

Each variable represents single value



### Create a list
As opposed to int, bool etc., a list is a compound data type; you can group values together:

`a = "is"`  
`b = "nice" `   
`my_list = ["my", "list", a, b]`

After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

#### Instructions

- Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.
- Print areas with the print() function.

In [20]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)


[11.25, 18.0, 20.0, 10.75, 9.5]


### Create list with different types

A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including `strings`, `floats`, `booleans`, etc.

The `printout` of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house.

The code in the editor is the start of a solution. For some of the areas, the name of the corresponding room is already placed in front. Pay attention here! `"bathroom"` is a string, while `bath` is a variable that represents the float 9.50 you specified earlier.

#### Instructions

- Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings `"hallway"`, `"kitchen"` and `"bedroom"` at the appropriate locations.
- Print `areas` again; is the printout more informative this time?

In [21]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


### List of lists

As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script in the editor can already give you an idea.

Don't get confused here: `"hallway"` is a string, while `hall` is a variable that represents the float `11.25` you specified earlier.

#### Instructions

- Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
- Print out `house`; does this way of structuring your data make more sense?
- Print out the type of `house`. Are you still dealing with a list

In [22]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


### Subsetting lists

**Subsetting lists:** This is accessing elements of a list

- Python uses indexes(0, 1, 2, ..., n).
- We use sapuare brackets.
- Lists are zero-indexed i.e starts with zero.
- Negative indexing - access elements from the end of a list.


`fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]`

`fam['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]`   

`fam[3]        #1.68`

`fam[6]        #'dad'`   

`fam[-1]       #1.89`   

`fam[7]        #1.89`



### List slicing 

**List slicing:** Selecting multiple elements from a list, thus creating a new list.

- Specify a range. E.x `fam[3:5]`. 
- Syntax - `[Start(Inclusive) : End(Exlusive)]`.
- `fam[:4]` - Start from zero(0) upto `3`.
- `fam[4:]` - List all elements from index `4` upto and including the last element.


`fam['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]`   

`fam[3:5]    #[1.68, 'mom']`  

`fam[1:4]    #[1.73, 'emma', 1.68]`

`fam[:4]    #['liz', 1.73, 'emma', 1.68]`  

`fam[5:]    #[1.71, 'dad', 1.89]`



### Subset and conquer

Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list `x` and then selects `"b"` from it. Remember that this is the second element, so it has index `1`. You can also use negative indexing.

`x = ["a", "b", "c", "d"]`  

`x[1]`  

`x[-3] # same result!`   

Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

#### Instructions

- Print out the second element from the `areas` list (it has the value `11.25`).
- Subset and print out the last element of `areas`, being `9.50`. Using a negative index makes sense here!
- Select the number representing the area of the living room `(20.0)` and print it out.

In [23]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


### Subset and calculate
After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:

`x = ["a", "b", "c", "d"]`  

`print(x[1] + x[3])`  

#### Instructions

- Using a combination of list subsetting and variable assignment, create a new variable, `eat_sleep_area`, that contains the sum of the area of the kitchen and the area of the bedroom.
- Print the new variable `eat_sleep_area`.

In [24]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


### Slicing and dicing

Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

`my_list[start:end]` - The start index will be included, while the end index is not.

The code sample below shows an example. A list with `"b"` and `"c"`, corresponding to indexes `1` and `2`, are selected from a list `x`:

`x = ["a", "b", "c", "d"]`  

`x[1:3]` - The elements with index `1` and `2` are included, while the element with index `3` is not.

#### Instructions

- Use slicing to create a list, `downstairs`, that contains the first `6` elements of areas.
- Do a similar thing to create a new variable, `upstairs`, that contains the last `4` elements of areas.
- Print both downstairs and upstairs using `print()`.

In [25]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


### Slicing and dicing (2)
In the video, Hugo first discussed the syntax where you specify both where to begin and end the slice of your list:

`my_list[begin:end]`

However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:

`x = ["a", "b", "c", "d"]`  

`x[:2]`  

`x[2:]`  

`x[:]`

#### Instructions

- Create `downstairs` again, as the first `6` elements of areas. This time, simplify the slicing by omitting the `begin` index.
- Create `upstairs` again, as the last `4` elements of areas. This time, simplify the slicing by omitting the `end `index.

In [26]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[6:]

### Subsetting lists of lists

You saw before that a Python list can contain practically anything; even other lists! To subset lists of lists, you can use the same technique as before: square brackets. Try out the commands in the following code sample in the IPython Shell:

`x = [["a", "b", "c"],`  

     `["d", "e", "f"],`  

     `["g", "h", "i"]]`  

`x[2][0]`  

`x[2][:2]`

`x[2]` results in a list, that you can subset again by adding additional square brackets.

What will `house[-1][1]` return? house, the list of lists that you created before, is already defined for you in the workspace. You can experiment with it in the IPython Shell.

In [27]:
house[-1][1]

9.5

### Manipulating Lists

- Change list elements


In [4]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)

fam[7] = 1.86
print(fam)

fam[0:2] = ["lisa", 1.74]
print(fam)




['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]


- Adding and Removing list elements

In [11]:
fam_ext = fam + ["me", 1.79] # Add elements in a list
print(fam_ext)

del(fam_ext[2:3])
print(fam_ext)

 

['lisa', 1.74, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]
['lisa', 1.74, 1.71, 'dad', 1.86, 'me', 1.79]


### Replace list elements
Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?

`x = ["a", "b", "c", "d"]`   
`x[1] = "r"`  

`x[2:] = ["s", "t"]`


For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

#### Instructions

- Update the area of the bathroom area to be `10.50 `square meters instead of `9.50`.
- Make the areas list more trendy! Change `"living room"` to `"chill zone"`.


In [13]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

### Extend a list
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the `+` operator:

`x = ["a", "b", "c", "d"]`

`y = x + ["e", "f"]`


You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the `areas` list?

#### Instructions

Use the `+` operator to paste the list `["poolhouse", 24.5]` to the end of the areas list. Store the resulting list as `areas_1`.
Further extend areas_1 by adding data on your garage. Add the string` "garage" `and float `15.45`. Name the resulting list `areas_2`.

In [14]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]
areas

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]
areas_1
 

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]
areas_2

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'poolhouse',
 24.5,
 'garage',
 15.45]

`NB:` There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the areas list.

In [18]:
del(areas_2[-4:-2])
areas_2

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'garage',
 15.45]

### Inner workings of lists

At the end of the video, Hugo explained how Python lists work behind the scenes. In this exercise you'll get some hands-on experience with this.

The Python code in the script already creates a list with the name `areas` and a copy named `areas_copy`. Next, the first element in the `areas_copy` list is changed and the `areas` list is printed out. If you hit Run Code you'll see that, although you've changed `areas_copy`, the change also takes effect in the `areas` list. That's because `areas` and `areas_cop`y point to the same list.

If you want to prevent changes in `areas_copy` from also taking effect in `areas`, you'll have to do a more explicit copy of the `areas` list. You can do this with `list()` or by using `[:]`.

#### Instructions

- Change the second command, that creates the variable `areas_copy`, such that `areas_copy` is an explicit copy of `areas`. 
- `After your edit, changes made to `areas_copy` shouldn't affect `areas`. Submit the answer to check this.

In [1]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]
